"""Rule-based baseline v3 for UMI grasp-feedback labels.

This version is intended for features generated by features8.py. It predicts
the natural-language feedback label from sensor-derived features only:

    too_low   -> contact happened, but effective hold/grasp was not established
    no_change -> stable enough grasp without excessive force/torque evidence
    too_high  -> excessive force/torque evidence during the hold stage

The rules intentionally do not use outcome metadata such as stable_grasp or
slip_or_drop, because this baseline is meant to approximate online feedback.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path
from typing import Any


LABELS = ("too_low", "no_change", "too_high")
PARAM_NAMES = (
    "too_low_force_loose_max",
    "too_low_torque_loose_max",
    "too_low_ty_loose_max",
    "high_force_strict_high",
    "high_force_strict_medium",
    "high_torque_loose_min",
    "high_tz_loose_min",
    "high_gelsight_bilateral_area_min",
    "high_gelsight_force_strict_min",
    "high_gelsight_torque_loose_min",
    "high_gelsight_min_diff_min",
    "paper_cup_rescue_grasp_min_delta",
    "paper_cup_rescue_hold_to_peak_min",
    "paper_cup_rescue_hold_to_peak_max",
)

OBJECT_PROFILE_OVERRIDES: dict[str, dict[str, float]] = {
    # Plastic bottles can show broad GelSight contact during correct stable grasps,
    # so force/torque rules are more reliable than raw contact area for too_high.
    "plastic_bottle": {
        "high_gelsight_bilateral_area_min": 999999.0,
        "high_gelsight_min_diff_min": 999999.0,
    },
    # Paper cups deform visibly under high force, but strict force hold alone can
    # over-fire on medium trials. Treat GelSight as supporting evidence near high.
    "paper_cup": {
        "too_low_force_loose_max": 0.36,
        "high_force_strict_high": 1.01,
        "high_gelsight_bilateral_area_min": 50.0,
        "high_gelsight_force_strict_min": 0.85,
        "high_gelsight_torque_loose_min": 0.90,
        "high_gelsight_min_diff_min": 1.45,
        "paper_cup_rescue_grasp_min_delta": 0.08,
        "paper_cup_rescue_hold_to_peak_min": 0.45,
        "paper_cup_rescue_hold_to_peak_max": 0.80,
    },
}


def parse_float(row: dict[str, Any], name: str, default: float = 0.0) -> float:
    value = row.get(name, "")
    if value is None or str(value).strip() == "":
        return default
    try:
        return float(value)
    except ValueError:
        return default


def normalize_profile_name(name: str) -> str:
    return name.strip().lower().replace("-", "_")


def infer_object_profile(row: dict[str, Any], forced_profile: str | None) -> str:
    if forced_profile:
        return normalize_profile_name(forced_profile)
    object_type = str(row.get("object_type", "") or "")
    if object_type.strip():
        return normalize_profile_name(object_type)
    object_id = str(row.get("object_id", "") or "")
    for profile_name in OBJECT_PROFILE_OVERRIDES:
        if profile_name in normalize_profile_name(object_id):
            return profile_name
    trial_dir = str(row.get("trial_dir", "") or "")
    for profile_name in OBJECT_PROFILE_OVERRIDES:
        if profile_name in normalize_profile_name(trial_dir):
            return profile_name
    return "global"


def params_for_row(
    row: dict[str, Any],
    base_params: dict[str, float],
    object_aware: bool,
    forced_profile: str | None,
) -> tuple[dict[str, float], str]:
    profile_name = infer_object_profile(row, forced_profile) if object_aware else "global"
    params = dict(base_params)
    params.update(OBJECT_PROFILE_OVERRIDES.get(profile_name, {}))
    return params, profile_name


def read_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError("No rows to write")

    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def predict_row(
    row: dict[str, Any],
    object_profile: str,
    too_low_force_loose_max: float,
    too_low_torque_loose_max: float,
    too_low_ty_loose_max: float,
    high_force_strict_high: float,
    high_force_strict_medium: float,
    high_torque_loose_min: float,
    high_tz_loose_min: float,
    high_gelsight_bilateral_area_min: float,
    high_gelsight_force_strict_min: float,
    high_gelsight_torque_loose_min: float,
    high_gelsight_min_diff_min: float,
    paper_cup_rescue_grasp_min_delta: float,
    paper_cup_rescue_hold_to_peak_min: float,
    paper_cup_rescue_hold_to_peak_max: float,
) -> tuple[str, str, float]:
    force_loose = parse_float(row, "effective_force_hold_3_5s_both_loose_contact_ratio")
    force_strict = parse_float(row, "effective_force_hold_3_5s_both_strict_contact_ratio")
    torque_loose = parse_float(row, "effective_torque_hold_3_5s_both_loose_contact_ratio")
    torque_strict = parse_float(row, "effective_torque_hold_3_5s_both_strict_contact_ratio")
    ty_loose = parse_float(row, "effective_ty_hold_3_5s_both_loose_contact_ratio")
    tz_loose = parse_float(row, "effective_tz_hold_3_5s_both_loose_contact_ratio")
    left_gelsight_area = parse_float(row, "left_gelsight_contact_area_max")
    right_gelsight_area = parse_float(row, "right_gelsight_contact_area_max")
    gelsight_area_min = min(left_gelsight_area, right_gelsight_area)
    gelsight_min_diff = parse_float(row, "effective_gelsight_min_diff_max")
    force_grasp_min_delta = parse_float(
        row, "effective_force_grasp_1_3s_min_delta_mean"
    )
    force_hold_to_peak_ratio = parse_float(
        row, "effective_force_hold_to_peak_min_delta_mean_ratio"
    )

    low_by_failed_hold = (
        force_loose < too_low_force_loose_max
        and torque_loose <= too_low_torque_loose_max
        and ty_loose <= too_low_ty_loose_max
    )
    paper_cup_early_grasp_rescue = (
        object_profile == "paper_cup"
        and low_by_failed_hold
        and force_grasp_min_delta >= paper_cup_rescue_grasp_min_delta
        and paper_cup_rescue_hold_to_peak_min
        <= force_hold_to_peak_ratio
        <= paper_cup_rescue_hold_to_peak_max
    )
    if paper_cup_early_grasp_rescue:
        rescue_score = min(
            force_grasp_min_delta / max(paper_cup_rescue_grasp_min_delta, 1e-6),
            force_hold_to_peak_ratio / max(paper_cup_rescue_hold_to_peak_min, 1e-6),
            paper_cup_rescue_hold_to_peak_max / max(force_hold_to_peak_ratio, 1e-6),
        )
        return "no_change", "paper_cup_early_grasp_rescue", rescue_score

    if low_by_failed_hold:
        low_score = max(
            (too_low_force_loose_max - force_loose) / max(too_low_force_loose_max, 1e-6),
            1.0 - torque_loose,
            1.0 - ty_loose,
        )
        return "too_low", "weak_force_and_no_torque_hold", low_score

    high_by_very_high_force = force_strict >= high_force_strict_high
    high_by_force_and_torque = (
        force_strict >= high_force_strict_medium
        and torque_loose >= high_torque_loose_min
    )
    high_by_torque_and_tz = (
        torque_loose >= high_torque_loose_min
        and tz_loose >= high_tz_loose_min
    )
    high_by_bilateral_gelsight_area = (
        gelsight_area_min >= high_gelsight_bilateral_area_min
        and (
            force_strict >= high_gelsight_force_strict_min
            or torque_loose >= high_gelsight_torque_loose_min
        )
    )
    high_by_gelsight_diff_and_force = (
        gelsight_min_diff >= high_gelsight_min_diff_min
        and force_strict >= high_gelsight_force_strict_min
    )

    if high_by_very_high_force:
        return "too_high", "very_high_force_strict_hold", force_strict
    if high_by_force_and_torque:
        score = min(force_strict / max(high_force_strict_medium, 1e-6), torque_loose)
        return "too_high", "high_force_and_torque_hold", score
    if high_by_torque_and_tz:
        score = min(torque_loose, tz_loose / max(high_tz_loose_min, 1e-6))
        return "too_high", "high_torque_and_tz_hold", score
    if high_by_bilateral_gelsight_area:
        score = gelsight_area_min / max(high_gelsight_bilateral_area_min, 1e-6)
        return "too_high", "bilateral_gelsight_contact_area", score
    if high_by_gelsight_diff_and_force:
        score = min(
            gelsight_min_diff / max(high_gelsight_min_diff_min, 1e-6),
            force_strict / max(high_force_strict_medium, 1e-6),
        )
        return "too_high", "gelsight_diff_and_force_hold", score

    stable_score = max(force_loose, torque_loose, ty_loose)
    return "no_change", "stable_non_excessive_hold", stable_score


def print_report(rows: list[dict[str, Any]]) -> None:
    total = len(rows)
    print(f"rows: {total}")
    if not total:
        return

    prediction_counts = Counter(row.get("rule_prediction", "") for row in rows)
    reason_counts = Counter(row.get("rule_reason", "") for row in rows)

    print("\nPrediction counts:")
    for label, count in prediction_counts.items():
        print(f"  {label}: {count}")

    print("\nReason counts:")
    for reason, count in reason_counts.items():
        print(f"  {reason}: {count}")

    if "final_instruction" not in rows[0]:
        return

    correct = sum(
        1
        for row in rows
        if row.get("final_instruction", "") == row.get("rule_prediction", "")
    )
    print(f"\nAccuracy: {correct}/{total} = {correct / total:.3f}")

    print("\nConfusion matrix: rows=true, cols=pred")
    print("true\\pred," + ",".join(LABELS))
    for true_label in LABELS:
        counts = []
        for pred_label in LABELS:
            counts.append(
                sum(
                    1
                    for row in rows
                    if row.get("final_instruction", "") == true_label
                    and row.get("rule_prediction", "") == pred_label
                )
            )
        print(true_label + "," + ",".join(str(count) for count in counts))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run object-aware rule-based baseline v3 on UMI features8 CSV."
    )
    parser.add_argument(
        "--features",
        required=True,
        help="Input features CSV, e.g. data_yue/pilot/plastic_bottle/features_contact5_v7.csv",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output CSV with rule_prediction columns. Default: <features>_rule_predictions_v2.csv",
    )
    parser.add_argument(
        "--no-object-aware",
        action="store_false",
        dest="object_aware",
        help="Disable object-specific threshold profiles and use only global CLI thresholds.",
    )
    parser.add_argument(
        "--object-profile",
        choices=("global", "plastic_bottle", "paper_cup"),
        default=None,
        help=(
            "Force one threshold profile for all rows. By default, the profile is "
            "inferred from object_type/object_id/trial_dir when available."
        ),
    )
    parser.add_argument(
        "--too-low-force-loose-max",
        type=float,
        default=0.25,
        help="Predict too_low when hold force loose ratio is below this and torque/ty are absent.",
    )
    parser.add_argument(
        "--too-low-torque-loose-max",
        type=float,
        default=0.05,
        help="Maximum hold torque loose ratio allowed for too_low.",
    )
    parser.add_argument(
        "--too-low-ty-loose-max",
        type=float,
        default=0.05,
        help="Maximum hold ty loose ratio allowed for too_low.",
    )
    parser.add_argument(
        "--high-force-strict-high",
        type=float,
        default=0.95,
        help="Predict too_high when force strict hold ratio is at least this value.",
    )
    parser.add_argument(
        "--high-force-strict-medium",
        type=float,
        default=0.50,
        help="Predict too_high when force strict is above this and torque is also high.",
    )
    parser.add_argument(
        "--high-torque-loose-min",
        type=float,
        default=0.95,
        help="Minimum torque loose hold ratio for too_high torque rules.",
    )
    parser.add_argument(
        "--high-tz-loose-min",
        type=float,
        default=0.80,
        help="Minimum tz loose hold ratio for too_high torque/tz rule.",
    )
    parser.add_argument(
        "--high-gelsight-bilateral-area-min",
        type=float,
        default=50.0,
        help=(
            "Predict too_high when both GelSight contact-area maxima are at least "
            "this value and force/torque hold evidence is also near high."
        ),
    )
    parser.add_argument(
        "--high-gelsight-force-strict-min",
        type=float,
        default=0.85,
        help=(
            "Minimum force strict hold ratio required before GelSight area/diff can "
            "upgrade a trial to too_high."
        ),
    )
    parser.add_argument(
        "--high-gelsight-torque-loose-min",
        type=float,
        default=0.90,
        help=(
            "Minimum torque loose hold ratio required before bilateral GelSight area "
            "can upgrade a trial to too_high."
        ),
    )
    parser.add_argument(
        "--high-gelsight-min-diff-min",
        type=float,
        default=1.45,
        help=(
            "Predict too_high when effective_gelsight_min_diff_max is at least "
            "this value and force strict hold ratio is near high. Set very high "
            "to disable this auxiliary rule."
        ),
    )
    parser.add_argument(
        "--paper-cup-rescue-grasp-min-delta",
        type=float,
        default=0.08,
        help=(
            "For paper_cup only: rescue a weak hold as no_change when the grasp "
            "stage already showed at least this bilateral force min-delta mean."
        ),
    )
    parser.add_argument(
        "--paper-cup-rescue-hold-to-peak-min",
        type=float,
        default=0.45,
        help=(
            "For paper_cup only: minimum hold/peak force response ratio for the "
            "early-grasp rescue."
        ),
    )
    parser.add_argument(
        "--paper-cup-rescue-hold-to-peak-max",
        type=float,
        default=0.80,
        help=(
            "For paper_cup only: maximum hold/peak force response ratio for the "
            "early-grasp rescue. Values near 1.0 look like late weak-contact "
            "growth and remain too_low."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    features_path = Path(args.features)
    output_path = (
        Path(args.output)
        if args.output
        else features_path.with_name(features_path.stem + "_rule_predictions_v3.csv")
    )

    rows = read_csv(features_path)
    base_params = {name: float(getattr(args, name)) for name in PARAM_NAMES}
    for row in rows:
        row_params, profile_name = params_for_row(
            row=row,
            base_params=base_params,
            object_aware=args.object_aware,
            forced_profile=args.object_profile,
        )
        prediction, reason, score = predict_row(
            row=row,
            object_profile=profile_name,
            too_low_force_loose_max=row_params["too_low_force_loose_max"],
            too_low_torque_loose_max=row_params["too_low_torque_loose_max"],
            too_low_ty_loose_max=row_params["too_low_ty_loose_max"],
            high_force_strict_high=row_params["high_force_strict_high"],
            high_force_strict_medium=row_params["high_force_strict_medium"],
            high_torque_loose_min=row_params["high_torque_loose_min"],
            high_tz_loose_min=row_params["high_tz_loose_min"],
            high_gelsight_bilateral_area_min=row_params[
                "high_gelsight_bilateral_area_min"
            ],
            high_gelsight_force_strict_min=row_params["high_gelsight_force_strict_min"],
            high_gelsight_torque_loose_min=row_params[
                "high_gelsight_torque_loose_min"
            ],
            high_gelsight_min_diff_min=row_params["high_gelsight_min_diff_min"],
            paper_cup_rescue_grasp_min_delta=row_params[
                "paper_cup_rescue_grasp_min_delta"
            ],
            paper_cup_rescue_hold_to_peak_min=row_params[
                "paper_cup_rescue_hold_to_peak_min"
            ],
            paper_cup_rescue_hold_to_peak_max=row_params[
                "paper_cup_rescue_hold_to_peak_max"
            ],
        )
        row["rule_profile"] = profile_name
        row["rule_prediction"] = prediction
        row["rule_reason"] = reason
        row["rule_score"] = f"{score:.6f}"

    write_csv(output_path, rows)
    print(f"Saved predictions to: {output_path}")
    print_report(rows)


if __name__ == "__main__":
    main()
